# Generated by Django 5.1.1 on 2025-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_delete_payment_piggybank_sum_deposits_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='how_paid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='when_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
