# Generated by Django 5.1.1 on 2025-01-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_deposits_branch_obligation_branch_obligation_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
