# Generated by Django 5.1.1 on 2025-01-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_deposits_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='to_count',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
