# Generated by Django 5.1.1 on 2025-01-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_delete_patientcount'),
        ('payment', '0007_obligation_to_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligation', to='patients.patient'),
        ),
    ]
