# Generated by Django 5.1.1 on 2025-01-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_deposits_patient_alter_obligation_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposits',
            old_name='ammonut',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='obligation',
            old_name='ammount',
            new_name='amount',
        ),
    ]
