# Generated by Django 5.1.1 on 2024-10-01 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
