# Generated by Django 5.1.1 on 2024-10-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_manager', '0002_delete_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
