# Generated by Django 5.1.1 on 2024-11-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('user_profile', '0002_profilecentraluser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('zwolnienie', 'Zwolnienie'), ('urlop', 'Urlop'), ('inne', 'Inne')], default='inne', max_length=30)),
                ('reason', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilecentraluser')),
            ],
        ),
    ]
