# Generated by Django 5.1.1 on 2024-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
