# Generated by Django 5.1.1 on 2024-11-10 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_date_event_end_time_event_start_time'),
        ('user_profile', '0005_remove_doctorschedule_date_doctorschedule_day_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='office',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='event.office',
                null=True,
                blank=True,
            ),
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilecentraluser')),
            ],
        ),
    ]
