# Generated by Django 5.1.1 on 2024-11-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_office'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
