# Generated by Django 5.1.1 on 2024-11-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_patien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='patien',
            new_name='patient',
        ),
    ]
