# Generated by Django 5.1.1 on 2024-11-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='profile',
            new_name='doctor',
        ),
    ]
