# Generated by Django 5.1.1 on 2024-11-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_tags_visittype_event_description_event_tags_and_more'),
        ('user_profile', '0007_alter_profilecentraluser_role_employeeschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant', to='user_profile.profilecentraluser'),
        ),
    ]
