# Generated by Django 5.1.1 on 2024-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_event_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='rep_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
