# Generated by Django 5.1.1 on 2024-11-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_is_rep_event_rep_id_alter_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
    ]
