# Generated by Django 5.1.1 on 2024-11-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_event_name'),
        ('patients', '0001_initial'),
        ('user_profile', '0007_alter_profilecentraluser_role_employeeschedule_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['doctor', 'date'], name='event_event_doctor__135da0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['office', 'date'], name='event_event_office__54d200_idx'),
        ),
    ]
