# Generated by Django 5.1.1 on 2024-12-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_identyficator_alter_branch_owner'),
        ('event', '0014_event_event_event_doctor__135da0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='branch.branch'),
        ),
    ]
