# Generated by Django 5.1.1 on 2024-12-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('event', '0015_absence_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='branch.branch'),
        ),
    ]
