# Generated by Django 5.1.1 on 2024-12-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('event', '0016_event_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='office', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='planchange',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='planchange', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='tags',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='branch.branch'),
        ),
        migrations.AddField(
            model_name='visittype',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='visittype', to='branch.branch'),
        ),
    ]
