# Generated by Django 5.1.1 on 2024-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('event', '0017_office_branch_planchange_branch_tags_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('branch', 'name')},
        ),
    ]
