# Generated by Django 5.1.1 on 2025-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_alter_tags_icon_alter_tags_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('started', 'Started'), ('in_progres', 'In_Progres'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='planned')),
            ],
        ),
    ]
