# Generated by Django 5.1.1 on 2025-01-06 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventstatus'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='event.eventstatus'),
        ),
    ]
