# Generated by Django 5.1.1 on 2025-01-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_event_cost_event_event_status'),
        ('payment', '0002_deposits_obligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.obligation'),
        ),
    ]
