# Generated by Django 5.1.1 on 2025-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_event_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('started', 'Started'), ('in_progres', 'In_Progres'), ('ended', 'Ended'), ('canceled', 'Canceled')], default='planned', max_length=255),
        ),
    ]
