# Generated by Django 5.1.1 on 2024-11-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_doctorschedule_date_doctorschedule_day_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day_num',
            field=models.IntegerField(default=8),
        ),
    ]
