# Generated by Django 5.1.1 on 2024-11-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_doctorschedule_day_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecentraluser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('doctor', 'Doctor'), ('assistant', 'Assistant'), ('reception', 'Reception'), ('none', 'None')], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilecentraluser')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorSchedule',
        ),
    ]
