# Generated by Django 5.1.1 on 2024-11-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_alter_branch_identyficator_alter_branch_owner'),
        ('user_profile', '0009_alter_profilecentraluser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecentraluser',
            name='owner',
        ),
        migrations.AddField(
            model_name='profilecentraluser',
            name='branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_central_user', to='branch.branch'),
        ),
    ]
