# Generated by Django 5.1.1 on 2024-12-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_remove_profilecentraluser_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecentraluser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
