# Generated by Django 5.1.1 on 2024-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_profilecentraluser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecentraluser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('assistant', 'Assistant'), ('reception', 'Reception'), ('none', 'None')], default='none', max_length=30),
        ),
    ]
