# Generated by Django 5.1.1 on 2024-12-07 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('user_profile', '0012_alter_profilecentraluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeschedule',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='branch.branch'),
        ),
    ]
