# Generated by Django 5.1.1 on 2024-12-07 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('user_profile', '0013_employeeschedule_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecentraluser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_central_user', to='branch.branch'),
        ),
    ]
