# Generated by Django 5.1.1 on 2024-11-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='vat',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
