# Generated by Django 5.1.1 on 2024-10-01 00:34

import datetime
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='schema_name',
            field=models.CharField(db_index=True, default=datetime.datetime(2023, 10, 1, 0, 0), max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
            preserve_default=False,
        ),
    ]
