# Generated by Django 5.1.1 on 2024-10-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_institution_created_institution_schema_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, unique=True),
        ),
    ]
