# Generated by Django 5.1.1 on 2024-12-09 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('event', '0017_office_branch_planchange_branch_tags_branch_and_more'),
        ('patients', '0002_patient_branch'),
        ('user_profile', '0014_alter_profilecentraluser_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('tooth', models.CharField(default='Brak', max_length=255)),
                ('anesthesia', models.CharField(max_length=1024)),
                ('details', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='branch.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilecentraluser')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='event.event')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='patients.patient')),
            ],
        ),
    ]
