# Generated by Django 5.1.1 on 2024-12-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(),
        ),
    ]
