# Generated by Django 5.1.1 on 2024-12-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('event', '0017_office_branch_planchange_branch_tags_branch_and_more'),
        ('patients', '0004_alter_treatment_date'),
        ('user_profile', '0014_alter_profilecentraluser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='anesthesia',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='branch.branch'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.profilecentraluser'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='event.event'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tooth',
            field=models.CharField(blank=True, default='Brak', max_length=255, null=True),
        ),
    ]
