# Generated by Django 5.1.1 on 2024-12-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('patients', '0005_alter_treatment_anesthesia_alter_treatment_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('true', 'True'), ('pending', 'Pending'), ('false', 'False')], default='false', max_length=30),
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentplan', to='branch.branch')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.treatmentplan'),
        ),
    ]
