# Generated by Django 5.1.1 on 2025-01-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_identyficator'),
        ('patients', '0006_treatment_procedure_treatment_status_treatmentplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_count', to='branch.branch')),
            ],
        ),
    ]
