# Generated by Django 5.1.1 on 2025-01-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientCount',
        ),
    ]
