# Generated by Django 5.1.1 on 2025-01-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_delete_patientcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='tooth',
        ),
        migrations.CreateModel(
            name='Teeth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.treatment')),
            ],
        ),
        migrations.CreateModel(
            name='TeethInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=255)),
                ('teeth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.teeth')),
            ],
        ),
    ]
