# Generated by Django 5.1.1 on 2025-01-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_remove_treatment_tooth_teeth_teethinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teeth',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='patients.treatment'),
        ),
    ]
