# Generated by Django 5.1.1 on 2025-01-22 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_alter_teeth_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teethinfo',
            name='teeth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='patients.teeth'),
        ),
    ]
