# Generated by Django 5.1.1 on 2024-11-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_branch_name_alter_branch_owner'),
        ('user_profile', '0009_alter_profilecentraluser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='identyficator',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches_owner', to='user_profile.profilecentraluser'),
        ),
    ]
